### ISSUE TITLE
v1 tag doesn't point to latest release

### ISSUE THREAD

**Issue by bastianschwarz** [CharMixer/auto-changelog-action#12]
The v1 tag doesn't seem to be up to date so when using `@v1` the first prerelease instead of 1.1 will be used. This basically prevents using semver version constraints.

> Move the major version tag (such as v1, v2) to point to the Git ref of the current release. For more information, see "Git basics - tagging."

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#using-tags-for-release-management

**Comment by charmixer** [comment]
Thanks, that's a good point.
I'm looking for a idiomatic way of moving the git tag to another commit, but have only found hacked versions.

If you have a good way of doing so, then please let me know :)

**Comment by bastianschwarz** [comment]
Huh, I thought examples for this were actually easier to find since a lot of actions do this. But google only finds lots of actions that create semantic releases but don't move a "major" tag with them.

Then I found this which makes a lot of sense and should be rather easy: https://github.community/t/version-numbering-for-actions/16307/5

Also in the same thread: https://github.com/marketplace/actions/actions-tagger
Not sure if/how it works.

And lastly from those who should know what they are doing (hopefully): https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

```bash
git tag -fa v1 -m "Update v1 tag"
git push origin v1 --force
```

Should be easy enough to do this in a workflow that runs on published releases and parse the major version from the current tag.

If you lack the time I might be able to open a PR during the holidays though I wouldn't hold my breath on that one. And then again: Dependabot also checks action dependencies so it's not that big of a deal.

**Comment by charmixer** [comment]
Found out that I could just move the release to point to the latest tag. 
Easy fix wihtout any git magic needed. :+1:

**Comment by charmixer** [comment]
Thinking a bit more about this, it probably isn't a fix...
I guess git tags is how github-action makes checkouts, so changing the github release wouldn't affect anything.

**Comment by charmixer** [comment]
Manually fixing it for now.

This snippet seems to work, for future releases.
```
git tag -f v1 v1.2
git push --tags --force
```
