### ISSUE TITLE
GHA fails when a 'main' branch

### ISSUE THREAD

**Issue by jstammers** [CharMixer/auto-changelog-action#16]
I've encountered an error when trying to create a changelog for a project that uses a `main` branch rather than a `master` one.

Here is the output that I see in the GHA log
> Running: github_changelog_generator --user **** --project **** --release-branch master  --output CHANGELOG.md --token ***          
> /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/****/****/compare/e224...1e42...master: 404 - Not Found // See: https://docs.github.com/rest/reference/repos#compare-two-commits (Octokit::NotFound)

**Comment by charmixer** [comment]
Did you change this line:
```
git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
```
to `HEAD:main`?

You might also want to change `release_branch` config param.

I can't really see much from the error description given.

**Comment by jstammers** [comment]
I hadn't changed 
```
 git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
```
as I'd blindly copied it from a previous repo.
Changing it to `HEAD:main` solved the problem
