### ISSUE TITLE
New official repo for generator docker images

### ISSUE THREAD

**Issue by ghost** [CharMixer/auto-changelog-action#17]
Hi, just wanted point out that there is new repo for docker images:

https://hub.docker.com/r/githubchangeloggenerator/github-changelog-generator/tags?page=1&ordering=last_updated

You can see that from the readme example https://github.com/github-changelog-generator/docker-github-changelog-generator

**Comment by charmixer** [comment]
Thanks for fixing this.

I've released it as v1.3 (v1 is also pointing to it)
